<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElApp.Watch.Domain\ElApp.Watch.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
  </ItemGroup>

</Project>
